# Generated by Django 5.2.7 on 2025-11-14 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataPagamento', models.DateField(max_length=10, verbose_name='Data')),
                ('valorPago', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valorPago')),
                ('metodoPagamento', models.CharField(choices=[('boleto', 'Boleto'), ('cartao', 'Cartão de Crédito'), ('pix', 'PIX')], default='cartao', max_length=20, verbose_name='metodoPagamento')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrato.contrato')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['id'],
            },
        ),
    ]
