# Generated by Django 5.2.7 on 2025-11-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='valorPago',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='valorPago'),
        ),
    ]
