# Generated by Django 5.2.7 on 2025-11-14 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroContrato', models.CharField(max_length=50, verbose_name='Numero Contrato')),
                ('dataInicio', models.DateField(verbose_name='Data Inicio')),
                ('dataFim', models.DateField(verbose_name='Data Fim')),
                ('valorTotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total')),
                ('status', models.CharField(choices=[('andamento', 'Em andamento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='andamento', max_length=20, verbose_name='Status')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['id'],
            },
        ),
    ]
