# Generated by Django 5.2.7 on 2025-11-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome fornecedor')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('telefone', models.CharField(max_length=9, verbose_name='telefone')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('endereco', models.CharField(max_length=50, verbose_name='endereco')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['id'],
            },
        ),
    ]
