# Generated by Django 5.2.7 on 2025-11-14 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrato', '0001_initial'),
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantidade')),
                ('valorUnitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preco unitario')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrato.contrato')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servico.servico')),
            ],
            options={
                'verbose_name': 'Item do contrato',
                'verbose_name_plural': 'Itens do contrato',
                'ordering': ['id'],
                'unique_together': {('contrato', 'servico')},
            },
        ),
    ]
