# Generated by Django 5.2.7 on 2025-11-14 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeArquivo', models.CharField(max_length=50, verbose_name='nome Arquivo')),
                ('tipoArquivo', models.CharField(choices=[('pdf', 'pdf'), ('jpeg', 'JPEG'), ('PNG', 'PNG')], default='PDF', max_length=20, verbose_name='tipo Arquivo')),
                ('dataUpload', models.DateField(max_length=10, verbose_name='data Upload')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrato.contrato')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
                'ordering': ['id'],
            },
        ),
    ]
