# Generated by Django 5.2.7 on 2025-11-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
                ('descricao', models.CharField(max_length=50, verbose_name='descricao')),
                ('precoBase', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='precoBase')),
            ],
        ),
    ]
