# Generated by Django 5.2.7 on 2025-11-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('senha', models.CharField(max_length=15, verbose_name='senha')),
                ('cargo', models.CharField(choices=[('estagiario', 'Estagiario'), ('jovemAprendiz', 'Jovem Aprendiz'), ('efetivado', 'Efetivado')], default='efetivado', max_length=20, verbose_name='cargo')),
            ],
            options={
                'verbose_name': 'funcionario',
                'verbose_name_plural': 'funcionarios',
                'ordering': ['id'],
            },
        ),
    ]
